# Configuración MQTT de Cafetera.
# Editá este archivo y volvé a instalar la app para que tome los cambios.
# broker: tcp://host:1883  o  ssl://host:8883
mqtt.broker=tcp://test.mosquitto.org:1883
mqtt.topic=cl/kope/iot/cafetera
mqtt.payload={"action": "turn-on","pulso_ms": 500}
mqtt.qos=2
mqtt.clientId=cafetera-kp
mqtt.username=
mqtt.password=
# debug=true muestra en pantalla el broker, el tópico, el mensaje y el token
debug=false
